# Generated by Django 5.2.1 on 2025-09-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.URLField(verbose_name='Original Link')),
                ('short_link', models.URLField(verbose_name='Modified Link')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_clicked', models.DateField(auto_now_add=True, verbose_name='Day Clicked')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('url_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_link', to='url_shortner.urlmodel')),
            ],
        ),
    ]
