# Generated by Django 5.2.1 on 2025-09-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='uuid',
            field=models.CharField(default='jfod-skdp', max_length=10, verbose_name='uuid'),
        ),
    ]
