# Generated by Django 5.2.1 on 2025-09-10 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_urlmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1fcbc835-aebf-4ec4-94c5-21081135efb5'), max_length=10, verbose_name='uuid'),
        ),
    ]
