# Generated by Django 5.2.1 on 2025-09-10 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0003_alter_urlmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='uuid',
            field=models.CharField(default=uuid.UUID('6dc6ded8-83ed-4748-8935-1cf1c4035f4c'), max_length=10, verbose_name='uuid'),
        ),
    ]
