# Generated by Django 5.2.1 on 2025-09-10 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0004_alter_urlmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='long_link',
            field=models.CharField(max_length=200, verbose_name='Original Link'),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='short_link',
            field=models.CharField(max_length=200, verbose_name='Modified Link'),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f7995dd4-8214-4347-85ef-87534723aea0'), max_length=10, verbose_name='uuid'),
        ),
    ]
