# Generated by Django 5.2.1 on 2025-09-10 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0005_alter_urlmodel_long_link_alter_urlmodel_short_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a03b40a9-0265-448d-be0e-fea6845a685e'), max_length=10, verbose_name='uuid'),
        ),
    ]
