# Generated by Django 5.2.1 on 2025-09-10 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0006_alter_urlmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, verbose_name='uuid'),
        ),
    ]
