# Generated by Django 5.2.1 on 2025-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0007_alter_urlmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='link_to',
            field=models.CharField(default='Kaggle', max_length=50, verbose_name='Link Destination'),
        ),
    ]
