# Generated by Django 5.2.1 on 2025-09-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0008_urlmodel_link_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='link_to',
            field=models.CharField(max_length=50, verbose_name='Link Destination'),
        ),
    ]
