# Generated by Django 5.2.1 on 2025-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0009_alter_urlmodel_link_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='time_clicked',
            field=models.CharField(verbose_name='Day Clicked'),
        ),
    ]
