# Generated by Django 5.2.1 on 2025-09-11 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0010_alter_click_time_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='time_clicked',
            field=models.DateField(default=datetime.date(2025, 9, 11), verbose_name='Day Clicked'),
        ),
    ]
