# Generated by Django 5.2.1 on 2025-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0011_alter_click_time_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='time_clicked',
            field=models.DateField(verbose_name='Day Clicked'),
        ),
    ]
