# Generated by Django 5.2.1 on 2025-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0012_alter_click_time_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='number_of_time_clicked',
            field=models.IntegerField(default=0, verbose_name='TImes Clicked'),
        ),
    ]
