# Generated by Django 5.2.1 on 2025-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0013_click_number_of_time_clicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='number_of_time_clicked',
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='number_of_times_clicked',
            field=models.IntegerField(default=0, verbose_name='TImes Clicked'),
        ),
    ]
