# Generated by Django 5.2.1 on 2025-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0014_remove_click_number_of_time_clicked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevenDayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1_date', models.DateField()),
                ('day1_value', models.CharField(max_length=20)),
                ('day2_date', models.DateField()),
                ('day2_value', models.CharField(max_length=20)),
                ('day3_date', models.DateField()),
                ('day3_value', models.CharField(max_length=20)),
                ('day4_date', models.DateField()),
                ('day4_value', models.CharField(max_length=20)),
                ('day5_date', models.DateField()),
                ('day5_value', models.CharField(max_length=20)),
                ('day6_date', models.DateField()),
                ('day6_value', models.CharField(max_length=20)),
                ('day7_date', models.DateField()),
                ('day7_value', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
