# Generated by Django 5.2.1 on 2025-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0015_sevendaydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevendaydata',
            name='day1_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day2_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day3_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day4_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day5_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day6_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day7_date',
            field=models.DateField(default=None),
        ),
    ]
