# Generated by Django 5.2.1 on 2025-09-13 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0016_alter_sevendaydata_day1_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevendaydata',
            name='day2_date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day3_date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day4_date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day5_date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day6_date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day7_date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
    ]
