# Generated by Django 5.2.1 on 2025-09-14 20:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0018_alter_sevendaydata_day2_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevendaydata',
            name='click_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date_clicked', to='url_shortner.click'),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day2_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 48, 29, 75945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day3_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 48, 29, 75945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day4_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 48, 29, 75945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day5_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 48, 29, 75945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day6_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 48, 29, 75945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day7_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 48, 29, 75945, tzinfo=datetime.timezone.utc)),
        ),
    ]
