# Generated by Django 5.2.1 on 2025-09-14 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0019_sevendaydata_click_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevendaydata',
            name='day2_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 50, 50, 832278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day3_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 50, 50, 832278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day4_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 50, 50, 832278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day5_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 50, 50, 832278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day6_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 50, 50, 832278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sevendaydata',
            name='day7_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 20, 50, 50, 832278, tzinfo=datetime.timezone.utc)),
        ),
    ]
