# Generated by Django 5.2.1 on 2025-09-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0020_alter_sevendaydata_day2_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField(default=None)),
                ('day_value', models.CharField(max_length=20)),
                ('url_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_clicked', to='url_shortner.urlmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='SevenDayData',
        ),
    ]
